### PR TITLE
Fix some validation checking issues.

### LINKED ISSUE #127: Improve schema checking.
When loading a template with schema issues, it returns an error message that isn't really actionable.

```
failed to load resource policies/templates/gcp_resource_value_pattern_v1.yaml gcpresourcevaluepatternconstraintv1: failed to convert unstructured ConstraintTemplate to versioned: unable to convert unstructured object to templates.gatekeeper.sh/v1alpha1, Kind=ConstraintTemplate: cannot restore slice from bool
```

### PR DESCRIPTION
**Pull request by briantkennedy**
* Add schema check for validation section.
* Refactor redundancy in existing spec checks

Closes #127

### CODE REVIEW

File: pkg/gcv/configs/schemav1beta1.go [hunk 1]
```diff
@@ -22,74 +22,11 @@ import (
...
-								},
-							},
-							SwaggerSchemaProps: spec.SwaggerSchemaProps{},
-							ExtraProps:         nil,
-						}),
-					},
-				},
-			},
+			"metadata": *refProperty("#metadata"),
+			"spec":     *refProperty("#betav1spec"),
```
Comment (t12g) [inline pkg/gcv/configs/schemav1beta1.go]: optional: since betav1spec is in schemav1alpha1.go now, should we consolidate these 2 files?

Comment (briantkennedy) [reply pkg/gcv/configs/schemav1beta1.go]: fixed
